import LDDE

l = LDDE.LDDE()

print("Vazia: ",l.estaVazia())
l.inserirInicio('C')
l.show()
print('____________________________')
l.inserirInicio('B')
l.show()
print('____________________________')
l.inserirInicio('A')
l.show()
print('____________________________')
l.inserirFim('D')
l.show()
print('____________________________')
l.showReverso()
print('____________________________')
l.inserirFim('1')
l.show()
print('____________________________')
l.removerInicio()
l.show()
print('____________________________')
l.removerFim()
l.show()
print('____________________________')
print("Primeiro Elemento da Lista: ",l.getPrim())
print("Último Elemento da Lista: ",l.getUlt())
print("Lista Vazia: ",l.estaVazia())
print('____________________________')
l.inserirAposDet('K', 'D')
l.show()
print('____________________________')
l.remover('B')
l.show()
print('____________________________')
